add Azure SSO
binkhq/api-reflector pull request #2
Opened 2021-09-13 13:21 UTC by mmjjoozz

2021-09-14 09:07 UTC, Mick-Cadac commented on api_reflector/admin.py
> +                assert resp.ok
Please change the asserts to a check. Asserts can be optimised out if certain flags are set.

2021-09-14 09:08 UTC, Mick-Cadac commented on api_reflector/admin.py
> +                assert resp.ok
Please change the asserts to a check. Asserts can be optimised out if certain flags are set.

2021-09-14 11:24 UTC, backwardspy requested changes
Looks good so far. I have a few comments after trying it out locally.

**There seems to be no way to disable authentication.**

Requiring every developer to set up Azure SSO before they can use the project is not ideal. My suggestion is to provide an `azure_auth_enabled` setting that is false by default. That setting can then be used to decide whether to restrict the admin views, and register the azure blueprint in the API.

If you add that setting, I would also suggest changing the other azure settings so that they're optional unless the auth is enabled. I think you can achieve this with a [custom validator](https://pydantic-docs.helpmanual.io/usage/validators/) on each setting.

There should be some documentation written in the README to cover how to enable authentication. One other thing I had to change to make authentication work is setting this environment variable in my `.env` file:

```
OAUTHLIB_INSECURE_TRANSPORT=1
```

**Redirect to root after login**

When I was testing, after I logged into my Microsoft account I was redirected back to `/` instead of `/admin/`. It would be nice if the application remembered which URL the user was trying to navigate to, and redirected them there. I believe this is supported in OAuth, so it's likely that `flask-dance` provides functionality for this.

2021-09-14 11:26 UTC, backwardspy commented on settings.py
> +    azure_tenant: str
Very minor comment, but I'd prefer if these settings were visually separated from `secret_key`. I'd like to keep the settings grouped together with blank lines between each group to hopefully assist people's understanding of what these settings do.

2021-09-16 15:28 UTC, backwardspy approved these changes
lgtm

2021-09-16 15:37 UTC, Mick-Cadac approved these changes

2021-09-16 15:38 UTC, merged